/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Audino;

import java.io.File;
import org.apache.tika.metadata.Metadata;
import java.io.IOException;
import Audino.MetadataParser;

public class App {
    // public static void main(String[] args) {
    //     try {
    //         File folder = new File("I:/Temp/wavtest");
    //         for (File fileEntry : folder.listFiles()) {
    //             Metadata parsed = MetadataParser.parseAudio(fileEntry.getCanonicalPath());
    //             System.out.println(parsed.toString());
    //         }
    //     } catch (IOException e) {
    //         // Nope
    //         e.printStackTrace();
    //     }
    // }
}
